name: Feature request
description: Suggest a feature for Oh My Zsh
labels: 'Feature'
body:
  - type: input
    attributes:
      label: Is your feature request related to a particular plugin or theme? If so, specify it.
      description: The name of the plugin, theme or alias that you would like us to improve.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A description of what the problem is. 
      placeholder: Ex. I'm always frustrated when...
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A description of any alternative solutions or features you've considered. This can also include other plugins or themes.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context, screenshots or discord conversations about the feature request here. Also if you have any PRs related to this issue that are already open that you would like us to look at.
  - type: textarea
    attributes:
      label: Related Issues
      description: Is there any open or closed issues that is related to this feature request? If so please link them below!
